# =========================
# Specify years of interest
# =========================

# Indicate years by list (vs. start/stop/increment) setting years_by_list to True, False otherwise.
# Make sure to have the appropriate year information specified.  The
# Python script will select which settings to use, based on this value.
years_by_list: False


# list of specific years 
years:
  - '1981'

# List of years,  except inline format
#years:  ['1970', '1973','1981']

# or indicate years by start, end, increment
start_year: '1981'
end_year: '1981'
year_increment: 1


# ===============================================
# Specify months of interest
# ===============================================

# Specify months either by a list of months, or by start/end/increment
# Set months_by_list to True to specify a list, False otherwise.
# Python script will determine which settings to use, based on the value of
# months_by_list.
months_by_list: False

months_list:
  - '01'
  - '05'
  - '07'

# same as above, except using inline format
#months_list: ['01', '05', '07']


# months by start/end/increment
month_start: '01'
month_end:  '08'
month_increment: '01'


# ===============================================
#  Specify input and output directory information
#  and the input and output filename templates
# ===============================================


#========================
# Input dir and filename
#========================

# Specifically set a full dir path
#input_dir: '/Users/username/NA-CORDEX/Data/wrf_d01'

# or use an environment variable that is already set (via .bash_profile, .bashrc, or export)
input_dir:  ${INPUT_DIR}

# or specify an input directory:
#input_dir: /Users/username/NA-CORDEX/Data/processed

# Use year and month placeholders. The Python script will replace these placeholders by the
# years and months settings (from above).
input_filename_template: "tas_NAM-12_ERA5_evaluation_r1i1p1f1_NCAR_WRF461_v1-r1_hr_${YEAR}-${MONTH}"

# Specify the input filename extension, if unspecified, assume there is no filename
# extension for netCDF files.
input_filename_extension: .nc

#========================
# Output dir and filename
#========================
output_dir: ${OUTPUT_DIR}
#output_dir: '/Users/username/NA-CORDEX/output'

# Use the year and month placeholders based on the year and month settings
# (specified above). Substitution with actual year and month will be performed in the Python
# script
output_filename_template: "tas_NAM-12_ERA5_evaluation_r1ip1f1_NCAR_WRF461_v1-r1_hr"

# ==================
# Data variable of interest
# ==================
data_var: 'tas'

# If temp is in Kelvin, convert to degrees Celsius
# default is True
convert_to_celsius: True

# ==============
#  Plot specifics
# ==============

# "Areas" of interest (plotting will be in the order in which these are specified).
areas_of_interest:
  - 'entire'
  - 'region'
  - 'point'

# Titles
region_title: 'Great Lakes'
entire_title: 'Entire Region'
point_title: 'KBDU Boulder, CO'

# Define Great Lakes as lat,lon format based on upper and lower left and right
# points.
region_upper_left: [50.2, -89.5]
region_lower_left: [43.3,  -95.685]
region_upper_right: [ 44.0, -75.1,]
region_lower_right: [39.4, -82.6]

# Boulder Municipal Airport (KBDU)
point_lat: 40.04
point_lon: -105.23

# if undefined, set x-axis label to "Time (yr)" and y-axis to the long name from the
# input data file plus unit
x_axis_label:
y_axis_label:

# x_axis tick orientation: value in degrees
x_tick_rotation: 0

# orientation of panels 'vertical 'or 'horizontal' (if undefined, the default is vertical)
# 'horizontal' is 1 column, 3 rows of time-series plots and
# vertical is 3 rows, 1 column
panel_orientation: 'vertical'
plot_type: 'png'

# figure size
fig_width: 12
fig_height: 11

# Line color and width for all time-series subplots
line_color: "#4B0092"
line_width: 1

# For the hourly line, indicate the transparency, values below 1 are more
# transparent
alpha : 0.2
