# =========================
# Specify years of interest
# =========================

# Indicate years by list (vs. start/stop/increment) setting years_by_list to True, False otherwise.
# Make sure to have the appropriate year information specified.  The
# Python script will select which settings to use, based on this value.
years_by_list: True


# list of specific years 
years:
  - '1970'
  - '1973'
  - '1981'

# same as above, except inline format
#years:  ['1970', '1973','1981']

# or indicate years by start, end, increment
start_year: '1970'
end_year: '1980'
year_increment: 1


# ===============================================
# Specify months of interest
# ===============================================

# Specify months either by a list of months, or by start/end/increment
# Set months_by_list to True to specify a list, False otherwise.
# Python script will determine which settings to use, based on the value of
# months_by_list.
months_by_list: True

months_list:
  - '01'
  - '03'
  - '05'
  - '07'
  - '12'

# same as above, except using inline format
#months_list: ['01', '03', '05', '07', '12']


# months by start/end/increment
month_start: '01'
month_end: '12'
increment: '03'


# ===============================================
  Specify input and output directory information
  and the input and output filename templates
# ===============================================


#========================
# Input dir and filename
#========================

# Specifically set a full dir path
input_dir: '/Users/minnawin/NA-CORDEX/Data/wrf_d01'

# or use an environment variable that is already set (via .bash_profile, .bashrc, or export)
# input_dir: !ENV '$INPUT_DIR'

# Use year and month placeholders. The Python script will replace these placeholders by the
# years and months settings (from above).
input_filename_template: "wrfrst_d01_{$year!}-{$month!}-{$day!}_00:00:00"

#========================
# Output dir and filename
#========================
output_dir: '/Users/minnawin/NA-CORDEX/NA-CORDEX-CMIP6/output'

# Use the year and month placeholders based on the year and month settings
# (specified above). Substitution with actual year and month will be performed in the Python
# script
output_filename_template: "wrfrst_d01_{"

# ==================
# Data variable of interest
# ==================
data_var: 'T2'

# ==============
#  Plot specifics
# ==============
# Plotting information for 3-panels
panel1_title: 'Great Lakes'
panel2_title: 'Entire Region'
panel3_title: 'Near Boulder, CO'
panel1_line_marker_color: '#ffff0000'
panel2_line_marker_color: '#ffffffff'
panel3_line_marker_color: "orange"

# orientation of panels vertical or horizontal
panel_orientation: 'horizontal'
plot_type: 'png'
